# Generated by Django 4.2.18 on 2026-03-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/', verbose_name='Снимка')),
                ('filename', models.CharField(max_length=255, verbose_name='Име на файл')),
                ('datetime_taken', models.DateTimeField(blank=True, null=True, verbose_name='Дата и час на заснемане')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Географска ширина')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Географска дължина')),
                ('has_gps', models.BooleanField(default=False, verbose_name='Има GPS данни')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата на качване')),
            ],
        ),
    ]
